spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.30.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
server:
  context-path: /sell

# 一般使用logback-spring.xml配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log
#  path: E:/log/tomcat/
#  file: E:/log/tomcat/sell.log
#  level:
#    com.onejane.LoggerTest: debug


